
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 13 17:01:45 JST 2011
//----------------------------------------------------

package org.inouelab.coopqa.parser;

/** CUP generated class containing symbol constants. */
public class KBSym {
  /* terminals */
  public static final int AND = 3;
  public static final int NONVAR = 9;
  public static final int VARIABLE = 10;
  public static final int EOF = 0;
  public static final int IMPLY = 8;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int RPAREN = 6;
  public static final int NEG = 4;
  public static final int LPAREN = 5;
  public static final int OR = 7;
}

