
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 06 14:46:28 JST 2011
//----------------------------------------------------

package org.nii.cqa.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 3;
  public static final int NONVAR = 7;
  public static final int VARIABLE = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int RPAREN = 6;
  public static final int NEG = 4;
  public static final int LPAREN = 5;
}

